### ISSUE TITLE
Backup appimage is not working in arch-based distros using kde desktop environment

### ISSUE THREAD

**Issue by ducamagnifico** [internxt/drive-desktop-linux#24]
The appimage 2.4 will not open.  I am posting the output when opened in a terminal:

[26438:0922/185729.895673:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[26438:0922/185729.895695:ERROR:kwallet_dbus.cc(100)] Error contacting kwalletd (isEnabled)
[26438:0922/185729.895766:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[26438:0922/185729.895770:ERROR:kwallet_dbus.cc(72)] Error contacting klauncher to start kwalletd
[26438:0922/185729.895845:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[26438:0922/185729.895849:ERROR:kwallet_dbus.cc(418)] Error contacting kwalletd (close)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Safe Storage is not available
    at encryptToken (/tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/auth/service.ts:25:11)
    at i.<anonymous> (/tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/auth/handlers.ts:96:3)
    at i.emit (node:events:538:35)
    at i.emit (node:domain:475:12)
    at /tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/main.ts:110:14
(node:26438) UnhandledPromiseRejectionWarning: Error: Safe Storage is not available
    at encryptToken (/tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/auth/service.ts:25:11)
    at i.<anonymous> (/tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/auth/handlers.ts:96:3)
    at i.emit (node:events:538:35)
    at i.emit (node:domain:475:12)
    at /tmp/.mount_InternVXtVFA/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/main.ts:110:14
(Use `internxt-drive --trace-warnings ...` to show where the warning was created)
(node:26438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[26438:0922/185731.436358:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for sentry.internxt.com failed:
----- Certificate i=0 (CN=system:node:*.dev-hl.airbyte-dev.svc.cluster.local,O=system:nodes) -----
ERROR: No matching issuer found

**Comment by fvsegarra** [comment]
We're investigating this issue, please kindly send us the app log files alongside the link to this issue to [hello@internxt.com](mailto:hello@internxt.com)
Thank you
