### ISSUE TITLE
2.4 not working on Ubuntu based distro

### ISSUE THREAD

**Issue by RasheedAZ** [internxt/drive-desktop-linux#27]
Tested with both appimage and deb. I get this message after the certificate error mentioned in #7 
```

$ ./internxt_drive.appimage
[444143:1024/225245.024917:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for sentry.internxt.com failed:
----- Certificate i=0 (CN=system:node:*.dev-hl.airbyte-dev.svc.cluster.local,O=system:nodes) -----
ERROR: No matching issuer found


Renderer navigated to  /
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
[2024-10-24T09:53:13.551Z] [error] [Backup] error: UNKNOWN
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
[2024-10-24T09:54:01.970Z] [error] [Backup] error: UNKNOWN
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563
Error occurred in handler for 'get-usage': Error: Server not available
    at /tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/node_modules/@internxt/sdk/dist/photos/photos/index.js:169:19
    at process.usage (node:internal/process/task_queues:96:5)
    at t.UserUsageService.limitInBytes [as getPhotosUsage] (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:14:13)
    at async Promise.all (index 1)
    at t.UserUsageService.calculateUsage (/tmp/.mount_internBIrue9/resources/app.asar/dist/main/webpack:/internxt-drive/src/apps/main/usage/service.ts:31:37)
    at node:electron/js2c/browser_init:189:563


```

**Comment by fvsegarra** [comment]
We're investigating this issue, please kindly send us the app log files alongside the link to this issue to hello@internxt.com
Thank you

**Comment by bertvorenholt** [comment]
Hi @fvsegarra, are you interested in more of the same kind of logfiles? I have the same issue.

I also had to edit ~/.local/share/nautilus-python/extensions/internxt-virtual-drive.py to get rid of the "PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded."

I added
> import gi
> gi.require_version("Gtk", "4.0")

before "from gi.repository import Nautilus, GObject, Gtk, Gdk"

Happy to help. :-)

**Comment by denissignoretto** [comment]
I've got the same issue and backup is not working
